use p3_mersenne_31::Mersenne31;
use p3_field::{PrimeField32, PrimeCharacteristicRing};
use rand::random;

// We need to access the inner value for printing raw u32s
// Since 'value' is crate-public, we might need to use as_canonical_u32
// or just use Debug/Display if they are sufficient.

fn main() {
    println!("// M31 Golden Vectors generated by Rust");
    println!("// Format: A_val, B_val, Add_Res, Mul_Res");

    // 1. Edge Case: 0, 0
    print_case(Mersenne31::ZERO, Mersenne31::ZERO);

    // 2. Edge Case: 1, 1
    print_case(Mersenne31::ONE, Mersenne31::ONE);

    // 3. Edge Case: (P-1), 1  -> (-1) + 1 = 0
    let p_minus_1 = Mersenne31::new(0x7FFFFFFE); // 2^31 - 2
    print_case(p_minus_1, Mersenne31::ONE);

    // 4. Edge Case: (P-1), (P-1) -> (-1) * (-1) = 1
    print_case(p_minus_1, p_minus_1);

    // 5. Random cases
    for _ in 0..10 {
        // Generate random u32 within range
        let a_val: u32 = random::<u32>() % 2147483647;
        let b_val: u32 = random::<u32>() % 2147483647;
        
        let a = Mersenne31::new(a_val);
        let b = Mersenne31::new(b_val);
        
        print_case(a, b);
    }
}

fn print_case(a: Mersenne31, b: Mersenne31) {
    let sum = a + b;
    let prod = a * b;

    use std::fs::OpenOptions;
    use std::io::Write;

    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open("vectors.inc")
        .unwrap();

    // Output formatted for SystemVerilog copy-paste or easy parsing
    writeln!(file, 
        "// A={:08x}, B={:08x} -> Sum={:08x}, Prod={:08x}", 
        a.as_canonical_u32(), 
        b.as_canonical_u32(), 
        sum.as_canonical_u32(), 
        prod.as_canonical_u32()
    ).unwrap();
    
    writeln!(file,
        "check_vector(31'h{:x}, 31'h{:x}, 31'h{:x}, 31'h{:x});",
        a.as_canonical_u32(), 
        b.as_canonical_u32(), 
        sum.as_canonical_u32(), 
        prod.as_canonical_u32()
    ).unwrap();
}
